const testA = require('./inputValidation')
const testB = require('./playerPenalties')
const testC = require('./teamInitiation')
const testD = require('./closestPlayerChecks')
const testE = require('./playerCorners')
const testF = require('./setPieces')
const testG = require('./keepInBoundaries')
const testH = require('./miscPositionChecks')
const testI = require('./setGoalKick')

testA.runTest()
testB.runTest()
testC.runTest()
testD.runTest()
testE.runTest()
testF.runTest()
testG.runTest()
testH.runTest()
testI.runTest()