const testA = require('./inputValidation')
const testB = require('./teamInitiation')
const testC = require('./closestPlayerChecks')
const testD = require('./keepInBoundaries')
const testE = require('./miscPositionChecks')
const testF = require('./setPositionTests')
const testG = require('./relativePositions')

testA.runTest()
testB.runTest()
testC.runTest()
testD.runTest()
testE.runTest()
testF.runTest()
testG.runTest()